// Generated by scripts/render-partner-training.py. Regenerate media and this manifest together.
export const partnerTraining = {
  "title": "From first conversation to a paid business",
  "recorded": "2026-10-07",
  "duration": 1017.64,
  "voice": "Microsoft David Desktop",
  "chapters": [
    {
      "title": "Start with the right goal",
      "start": 0.0,
      "scenes": [
        {
          "heading": "Help the owner decide",
          "label": "Your training class",
          "points": [
            "Understand the business",
            "Show a real customer journey",
            "Help the owner set up and pay"
          ],
          "narration": "Welcome to Reviyo partner training. This class takes you from your first conversation with a business owner to a prepared account, a secure payment, and a useful handover. Your job is to help the owner understand the service and decide whether it fits their business. A good sale starts with listening and ends with a confident owner who knows what they bought."
        },
        {
          "heading": "Promise only what Reviyo does",
          "label": "Keep the explanation honest",
          "points": [
            "QR to a customer-controlled review draft",
            "No guaranteed stars, reviews or rankings",
            "No automatic posting to Google"
          ],
          "narration": "Reviyo helps customers describe a real visit and prepare a review draft. It does not guarantee five stars, a number of reviews, a Google ranking, or extra sales. The customer reads and edits the draft and posts on Google themselves. Never offer rewards for reviews or ask only happy customers. Pause this class whenever you want to practise a conversation. The examples are practice conversations, not customer testimonials."
        }
      ]
    },
    {
      "title": "Find a fit and ask permission",
      "start": 54.16,
      "scenes": [
        {
          "heading": "Look for a useful fit",
          "label": "Before you approach",
          "points": [
            "One business, one location, one Google profile",
            "Customers who can scan after a real visit",
            "An owner who wants a simpler review request"
          ],
          "narration": "Start with local businesses where customers visit and the owner wants a simpler way to request reviews. Restaurants, salons, stores, and service businesses can be suitable. Each plan covers one business, one location, and one Google Business Profile. Check whether the owner has the correct Google listing and can reach its review link. Do not invent lost revenue from a low review count. You are checking whether there is a real problem to solve."
        },
        {
          "heading": "Get permission for two minutes",
          "label": "Say this",
          "quote": "Hi, I help local businesses make it easier for customers to write a Google review. Is now a good time for a two-minute demo?",
          "narration": "You can say: Hi, I help local businesses make it easier for customers to write a Google review. Is now a good time for a two minute demo? If they are serving customers, ask when you can return. Speak to someone who can decide about the subscription. If they say no, thank them and stop. For a message, introduce yourself honestly and ask permission before sending a demonstration. Avoid repeatedly messaging people who have not agreed to a follow up."
        }
      ]
    },
    {
      "title": "Ask before you pitch",
      "start": 116.07,
      "scenes": [
        {
          "heading": "Learn their current process",
          "label": "Three discovery questions",
          "points": [
            "How do you ask customers for reviews now?",
            "Where do customers get stuck?",
            "Who would look after the QR and staff guidance?"
          ],
          "narration": "Ask three simple questions. How do you ask customers for reviews now? When a customer agrees, what usually stops them from finishing? Who would look after the QR code and explain it to your staff? Listen without interrupting. They may already have a Google QR code, or they may not want another tool. Learn whether the issue is finding the link, thinking of words, or finding time. Reviyo is useful only if its workflow addresses their need."
        },
        {
          "heading": "Reflect their answer back",
          "label": "Say this",
          "quote": "So customers are willing, but some do not know what to write. Let me show you how they can start with their own experience and edit a draft.",
          "narration": "For example, say: So customers are willing, but some do not know what to write. Let me show you how they can start with their own experience and edit a draft. Use their actual answer rather than this line if their problem is different. Confirm that you understood them before opening the demo. This keeps the conversation relevant and avoids a long list of features they do not need."
        }
      ]
    },
    {
      "title": "Deliver a clear opening pitch",
      "start": 173.82,
      "scenes": [
        {
          "heading": "The thirty-second explanation",
          "label": "Say this",
          "quote": "Reviyo gives your business a QR review page. Customers scan, describe their visit and get a draft they can edit. They choose whether to post it on Google themselves.",
          "narration": "Here is your opening explanation. Reviyo gives your business a QR review page. Customers scan it, choose relevant topics, and describe their real visit. They get a draft they can edit, then choose whether to post it on Google themselves. You can customise the topics and see activity in your dashboard. Would you like to see the customer journey on a phone? Keep this explanation short. Let the demo answer the next questions."
        },
        {
          "heading": "Connect features to daily work",
          "label": "Explain the practical benefit",
          "points": [
            "Printable QR: an easy place to start",
            "Review topics: prompts about a real visit",
            "Dashboard: see where people stop"
          ],
          "narration": "Explain benefits in everyday language. A printable QR gives staff one simple way to invite feedback. Relevant topics help a customer remember what they experienced. An editable draft gives them a starting point rather than asking them to write from a blank page. Dashboard activity helps the owner see where people stop. An open Google link is not proof that a review was published. Do not describe those clicks as verified Google reviews."
        }
      ]
    },
    {
      "title": "Demonstrate the customer journey",
      "start": 234.72,
      "scenes": [
        {
          "heading": "Show each step on a phone",
          "label": "Demo checklist",
          "points": [
            "Scan → choose topics → describe the visit",
            "Consent → draft → read and edit",
            "Open Google → customer chooses stars and posts"
          ],
          "narration": "Use an authorised demo page and explain that it is a demonstration. Show the QR being scanned and the review page opening. Select topics that relate to a genuine experience, explain the consent step, and show a draft. Read it together and change any inaccurate wording. Then explain how the customer opens Google, chooses their own stars there, and posts their own review. Stop before publishing a practice review to a real business."
        },
        {
          "heading": "Let the owner try it",
          "label": "Say this",
          "quote": "Please try editing this draft. Your customers have the same control. They can change it, discard it or choose not to post.",
          "narration": "Say: Please try editing this draft. Your customers have the same control. They can change it, discard it, or choose not to post. If the owner asks whether AI writes fake experiences, explain that customers must describe what really happened and correct the draft. The tool is an assistant for wording. It cannot create a genuine customer experience. Show a balanced example rather than pretending every visitor is delighted."
        }
      ]
    },
    {
      "title": "Explain plans without pressure",
      "start": 295.325,
      "scenes": [
        {
          "heading": "Three paid choices",
          "label": "Current plan prices",
          "points": [
            "₹500 for one month",
            "₹1,999 for six months",
            "₹2,999 for twelve months"
          ],
          "narration": "The current plans are five hundred rupees for one month, one thousand nine hundred and ninety nine rupees for six months, and two thousand nine hundred and ninety nine rupees for twelve months. These plans have the same included features. The term changes, not the number of locations. The longer terms are paid as the full amount shown, not as monthly instalments. Confirm the current price in the owner's checkout before payment, since prices may change after this recording."
        },
        {
          "heading": "Recommend what fits the owner",
          "label": "Say this",
          "quote": "Would a shorter commitment suit you, or do you already want to use this for a longer period? I can help you compare the total amount before you decide.",
          "narration": "Ask: Would a shorter commitment suit you, or do you already want to use this for a longer period? I can help you compare the total amount before you decide. Businesses prepared through the partner dashboard are paid setups and do not include a free trial. Say that clearly before inviting the owner. Do not promise a fourteen day trial or describe the commission waiting period as an owner's trial. Let the owner choose a plan based on their needs and budget."
        }
      ]
    },
    {
      "title": "Answer common objections",
      "start": 358.15,
      "scenes": [
        {
          "heading": "“I already have a Google QR”",
          "label": "Acknowledge, then show the difference",
          "quote": "That is a useful start. Reviyo adds prompts and an editable draft before the customer opens Google. If your current QR already solves the problem, you may not need another tool.",
          "narration": "If the owner says they already have a Google QR, reply: That is a useful start. Reviyo adds prompts and an editable draft before the customer opens Google. If your current QR already solves the problem, you may not need another tool. If they say customers can write reviews themselves, agree. Reviyo is optional help for people who want a starting point. Offer a short comparison and let the owner judge whether that extra help is useful."
        },
        {
          "heading": "“It is too expensive” or “no time”",
          "label": "Find the real concern",
          "points": [
            "Ask whether the issue is budget or usefulness",
            "Compare the shorter paid term if appropriate",
            "Offer help preparing the setup; owner stays in control"
          ],
          "narration": "For price concerns, ask: Is the main concern the budget, or whether your customers would use it? If the value is unclear, show the relevant part of the demo again. If commitment is the issue, explain the monthly paid option without promising results or unapproved discounts. For no time, say: I can prepare your business details and send an invitation. You still review them, create your own password, and pay yourself. Setup help does not mean taking over their account."
        },
        {
          "heading": "“Can you guarantee five stars?”",
          "label": "Keep expectations clear",
          "quote": "No. Customers decide their own rating and words. We make it easier to describe a real experience; we do not control the review or Google's decisions.",
          "narration": "If asked for guaranteed five stars, say: No. Customers decide their own rating and words. We make it easier to describe a real experience; we do not control the review or Google's decisions. If asked for a free trial, explain that the partner prepared route is paid only. If they want to discuss it with a colleague, offer the information and agree on a follow up time. A respectful pause is better than pushing someone into a purchase they do not understand."
        }
      ]
    },
    {
      "title": "Adapt the conversation to the business",
      "start": 455.475,
      "scenes": [
        {
          "heading": "Restaurant and salon examples",
          "label": "Use relevant topics",
          "points": [
            "Restaurant: food, service, atmosphere",
            "Salon: service, staff, cleanliness",
            "Ask every customer neutrally"
          ],
          "narration": "For a restaurant, say: After a visit, a customer can scan and describe the food, service, or atmosphere in their own words. For a salon, say: A customer can mention the service, staff, or cleanliness if those topics match their experience. Use the owner's language and real services. Topics are prompts, not instructions to praise the business. Train staff to invite customers neutrally rather than choosing only people who seem happy."
        },
        {
          "heading": "Sensitive services need care",
          "label": "Clinic and professional service examples",
          "quote": "Customers can share what they are comfortable making public. They should not include private health, financial or other sensitive details in a review.",
          "narration": "For a clinic or professional service, say: Customers can share what they are comfortable making public. They should not include private health, financial, or other sensitive details in a review. Do not ask a patient to describe a diagnosis or treatment outcome just to demonstrate the tool. Keep the focus on the voluntary review experience. Never imply that using Reviyo improves medical outcomes or that a professional endorses a claim they have not made."
        }
      ]
    },
    {
      "title": "Close with a clear next step",
      "start": 518.185,
      "scenes": [
        {
          "heading": "Check understanding first",
          "label": "Before asking for payment",
          "points": [
            "Owner understands what the product does",
            "Plan, full amount and paid setup are clear",
            "Permission to prepare details and email an invitation"
          ],
          "narration": "Before closing, check that the owner understands the customer flow, the limits of the service, the plan amount, and the absence of a free trial in this route. Ask: Does this solve the issue you mentioned? Which paid term suits you? Would you like me to prepare the details and send the invitation to your own email? Do not create an account or send an invitation on someone's behalf without their agreement."
        },
        {
          "heading": "If they are not ready",
          "label": "Say this",
          "quote": "Would you like a short summary, and is there a time you would prefer me to check back? If it is not useful for your business, that is fine.",
          "narration": "If they are not ready, say: Would you like a short summary, and is there a time you would prefer me to check back? If it is not useful for your business, that is fine. Record only the contact information they agree to share. Do not invent a deadline, claim places are running out, or repeatedly chase them. For a ready owner, read their email back carefully. That email is where the invitation and their account access will go."
        }
      ]
    },
    {
      "title": "Prepare the business correctly",
      "start": 575.44,
      "scenes": [
        {
          "heading": "Complete the partner setup form",
          "label": "In your partner dashboard",
          "points": [
            "Owner's email, business name and category",
            "Correct Google review link and optional logo",
            "Relevant topics; test the Google destination"
          ],
          "narration": "In your partner dashboard, find Set up a business for an owner. Enter the owner's own email, the correct business name, and the category. Prepare the Google review link, an optional logo, and relevant review topics. Suggested topics are a starting point; edit them for the actual business. Test the Google link and check that it opens the correct listing. A saved setup without the link still needs the correct destination before customers are asked to post on Google."
        },
        {
          "heading": "Check, save and invite",
          "label": "Use the right action",
          "points": [
            "Save without sending: keep a draft",
            "Save and invite owner: email the invitation",
            "Edit or resend a pending setup when needed"
          ],
          "narration": "Read the setup summary together. Use Save without sending if details still need checking. When the owner agrees and the details are ready, choose Save and invite owner. Saving the prepared setup registers your referral automatically; do not add a duplicate referral for it. If sending the email fails after saving, use the saved setup to resend. Do not create repeated drafts. A pending setup can be edited. Once the owner takes over, they manage their own business details."
        }
      ]
    },
    {
      "title": "Guide the invitation and password",
      "start": 641.555,
      "scenes": [
        {
          "heading": "The owner opens their email",
          "label": "Say this",
          "quote": "Open your Reviyo invitation on your device. Create and confirm your own password when asked. Keep it private; I do not need to see it.",
          "narration": "Tell the owner: Open your Reviyo invitation on your device. Create and confirm your own password when asked. Keep it private; I do not need to see it. New invited owners without a password must set one before continuing. Owners who already have a password keep it. Check the inbox and spam folder if the invitation is missing. If a link has expired, resend through the pending setup after any displayed waiting period. Never forward an access link to someone else."
        },
        {
          "heading": "Owner checks and accepts",
          "label": "Account ownership stays with the owner",
          "points": [
            "Review business details, topics and Google link",
            "Read the terms and make their own consent choices",
            "Choose a paid plan"
          ],
          "narration": "The owner then reviews the prepared business details and can correct them. Check the business name, review topics, and Google destination together. They read the terms and make their own consent choices. Do not tick a consent box for them. They choose a paid plan next. You can explain the screen, but never ask for a password, email code, bank code, or other private credentials. If a problem blocks the flow, pause and contact support rather than bypassing it."
        }
      ]
    },
    {
      "title": "Help the owner complete payment",
      "start": 707.45,
      "scenes": [
        {
          "heading": "Check the amount before checkout",
          "label": "Owner pays through Razorpay",
          "points": [
            "Confirm the selected term and full amount",
            "Owner completes UPI, card or netbanking",
            "Never send payment to a partner's personal account"
          ],
          "narration": "At the payment screen, ask the owner to confirm the selected plan, the full amount, and any terms shown. They open the Razorpay checkout and choose an available payment method such as UPI, card, or netbanking. Let them complete any verification privately. Reviyo subscription payments go through its checkout. Do not collect them into your personal bank account or UPI address, and do not ask the owner to send you a screenshot containing card details or an authentication code."
        },
        {
          "heading": "Wait for confirmation",
          "label": "Say this",
          "quote": "Please finish the payment on your device and return to Reviyo. We will wait for confirmation before downloading your QR.",
          "narration": "Say: Please finish the payment on your device and return to Reviyo. We will wait for confirmation before downloading your QR. A payment attempt or a bank debit screen alone is not confirmation that the setup is active. Wait for the confirmed result in Reviyo. Once payment is confirmed, the owner can download their QR and use the dashboard. If confirmation takes longer than expected, follow the next recovery steps instead of starting another payment."
        }
      ]
    },
    {
      "title": "Recover problems without a duplicate charge",
      "start": 770.92,
      "scenes": [
        {
          "heading": "Paid, but still waiting?",
          "label": "Check before retrying",
          "points": [
            "Use Check payment status",
            "Keep the payment reference and time",
            "Do not pay again while a charge is uncertain"
          ],
          "narration": "If the owner has paid but the site is still waiting, use Check payment status. Keep the payment reference, amount, and approximate time. Do not ask them to pay again while that charge is uncertain. For a cancelled or clearly failed attempt without a successful payment, the owner can retry the checkout. If money appears debited or the status is unclear, contact support at reviyo dot in with the reference and explain the screen shown. Do not share authentication codes or full bank details."
        },
        {
          "heading": "Invitation or setup problem?",
          "label": "A calm recovery conversation",
          "quote": "Let's check the saved setup and the message on your screen. We will resolve that step before making another account or payment.",
          "narration": "For an invitation problem, confirm the exact owner email, check spam, and resend the existing pending setup if needed. For incorrect business details, correct the saved draft before the owner takes over, or help the owner find their own settings afterwards. Say: Let's check the saved setup and the message on your screen. We will resolve that step before making another account or payment. Never promise that a pending transfer is definitely refunded or definitely successful without a confirmed status."
        }
      ]
    },
    {
      "title": "Hand over the QR and staff routine",
      "start": 837.32,
      "scenes": [
        {
          "heading": "Finish with a working handover",
          "label": "After confirmed payment",
          "points": [
            "Download and test the owner's actual QR",
            "Place it where customers can scan comfortably",
            "Show the dashboard and support contact"
          ],
          "narration": "After payment is confirmed, help the owner download the QR code or printable counter card. Scan the actual downloaded code and check the business page and Google destination. Put it where customers can scan comfortably, such as a counter or bill folder with the owner's permission. Show the owner how to sign in again, find their dashboard, and contact support. A sale is not complete just because payment succeeded; the owner should be able to use what they bought."
        },
        {
          "heading": "Give staff a neutral request",
          "label": "Say this to a customer",
          "quote": "If you would like to share your experience, you can scan this code. You can edit the draft and decide whether to post it on Google.",
          "narration": "Teach staff this request: If you would like to share your experience, you can scan this code. You can edit the draft and decide whether to post it on Google. Make that invitation available without judging whether a customer seems happy. No gifts, discounts, or demands for five stars. Ask permission to check back after the owner has used the QR. Review where the customer journey stops, rather than promising a specific number of reviews."
        }
      ]
    },
    {
      "title": "Practise the complete conversation",
      "start": 898.1,
      "scenes": [
        {
          "heading": "Opening → discovery → demo",
          "label": "Practice role-play · fictional example",
          "quote": "Partner: Is now a good time for a two-minute demo?\nOwner: What does it do?\nPartner: First, how do you ask for reviews today?",
          "narration": "Here is a fictional role play. Partner: Is now a good time for a two minute demo? Owner: What does it do? Partner: First, how do you ask for reviews today? Owner: We give people a link, but some do not know what to write. Partner: That is the part Reviyo can help with. Customers describe their visit and edit a draft before choosing whether to post on Google. May I show you? Owner: Yes, show me. Pause and practise that opening in your own words."
        },
        {
          "heading": "Plan → invitation → payment",
          "label": "Practice role-play · fictional example",
          "quote": "Partner: Which paid term suits you?\nOwner: Let's start with one month.\nPartner: I will prepare the details with your permission. You check them, set your password and pay through Razorpay.",
          "narration": "Continue the role play. Partner: Which paid term suits you? Owner: Let's start with one month. Partner: The current monthly price is five hundred rupees. This partner setup has no free trial. Shall I prepare your details and email the invitation? Owner: Yes. Partner: Please check your email address. You will open the invitation, set your own password, review the details, accept the terms, and pay through Razorpay. Once confirmed, we will download and test your QR. Owner: What if payment is delayed? Partner: We check its status before attempting another charge."
        },
        {
          "heading": "Your final readiness checklist",
          "label": "Replay any chapter when needed",
          "points": [
            "Listen, demonstrate and explain the paid plan",
            "Check email, link, invitation and owner password",
            "Confirm payment, test QR and hand over"
          ],
          "narration": "Before your first owner meeting, rehearse the short pitch, one objection, and the payment explanation. Know where the setup form and support contact are. Choose plans for the owner's needs rather than your commission. Your private dashboard explains earnings separately. Only a qualifying first annual payment can earn commission after the fourteen day checks; monthly and six month payments earn none. Keep bank details accurate, and remember that payout timing depends on checks and processing. You are ready when you can explain each step calmly and leave the owner in control."
        }
      ]
    }
  ]
} as const;
